twig:
    default_path: '%kernel.project_dir%/src/Controller/'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/Component/' : ~
        '%kernel.project_dir%/public' : public_path
    globals:
        icon_chef: '/assets/img/icons/chef.svg'