twig:
    default_path: '%kernel.project_dir%/src/Controller/'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/Component/' : ~
    globals:
        bootstrap_css: '/assets/css/bootstrap.css'
        bootstrap_js: '/assets/js/bootstrap.bundle.js'
        boostrap_icons_css: '/assets/css/bootstrap-icons-1.5.0/bootstrap-icons.css'
        jquery_js: '/assets/js/jquery-3.6.0.min.js'
        base_css: '/assets/css/custom/app_base.css'
        flashes_js: '/assets/js/custom/app_flashes.js'