version: '3.8'

services:
  app:
    build: 'https://github.com/t-ror/docker-badi-menu.git'
    volumes:
      - .:/var/www
    ports:
      - '80:80'
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mariadb:11.5.2
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db_data: