homepage:
    path: /
    controller: App\Controller\HomePage\HomePageController::default
login:
    path: /prihlaseni
    controller: App\Controller\User\UserController::login
logout:
    path: /odhlaseni
    controller: App\Controller\User\UserController::logout
register:
    path: /registrace
    controller: App\Controller\User\UserController::register
userEdit:
  path: /uzivatel/editace
  controller: App\Controller\User\UserController::edit
userDetail:
  path: /uzivatel/{url}
  controller: App\Controller\User\UserController::detail
householdList:
    path: /domacnost
    controller: App\Controller\Household\HouseholdController::list
householdSelect:
    path: /domacnost/vyber/{id}
    controller: App\Controller\Household\HouseholdController::select
householdListAdd:
    path: /domacnost/pridat
    controller: App\Controller\Household\HouseholdController::listAdd
householdAdd:
    path: /domacnost/pridat/{id}
    controller: App\Controller\Household\HouseholdController::add
mealList:
    path: /jidla
    controller: App\Controller\Meal\MealController::list
mealCreate:
    path: /jidlo/vytvorit
    controller: App\Controller\Meal\MealController::create
mealDetail:
  path: /jidlo/{url}
  controller: App\Controller\Meal\MealController::detail
mealEdit:
  path: /jidlo/upravit/{url}
  controller: App\Controller\Meal\MealController::edit
mealToggleFavorite:
  path: /jidlo/oblíbeny/{url}
  controller: App\Controller\Meal\MealController::toggleFavorite
mealToggleAbleToPrepare:
  path: /jidlo/umim-pripravit/{url}
  controller: App\Controller\Meal\MealController::toggleAbleToPrepare
mealTagList:
  path: /stitky
  controller: App\Controller\MealTag\MealTagController::list
mealTagDelete:
  path: /stitek/smazat/{id}
  controller: App\Controller\MealTag\MealTagController::delete
mealTagCreate:
  path: /stitek/vytvorit
  controller: App\Controller\MealTag\MealTagController::create
mealTagEdit:
  path: /stitek/upravit/{id}
  controller: App\Controller\MealTag\MealTagController::edit
mealTagProvideListData:
  path:  /meal-tag/list
  controller: App\Controller\MealTag\MealTagController::provideListData