homepage:
    path: /
    controller: App\Controller\HomePage\HomePageController::default
login:
    path: /prihlaseni
    controller: App\Controller\User\UserController::login
logout:
    path: /odhlaseni
    controller: App\Controller\User\UserController::logout
register:
    path: /registrace
    controller: App\Controller\User\UserController::register
householdList:
    path: /domacnost
    controller: App\Controller\Household\HouseholdController::list
householdSelect:
    path: /domacnost/vyber/{id}
    controller: App\Controller\Household\HouseholdController::select
householdListAdd:
    path: /domacnost/pridat
    controller: App\Controller\Household\HouseholdController::listAdd