homepage:
    path: /
    controller: App\Controller\HomePage\HomePageController::default
login:
    path: /prihlaseni
    controller: App\Controller\User\UserController::login
logout:
    path: /odhlaseni
    controller: App\Controller\User\UserController::logout
register:
    path: /registrace
    controller: App\Controller\User\UserController::register
householdList:
    path: /domacnost
    controller: App\Controller\Household\HouseholdController::list
householdSelect:
    path: /domacnost/vyber/{id}
    controller: App\Controller\Household\HouseholdController::select
householdListAdd:
    path: /domacnost/pridat
    controller: App\Controller\Household\HouseholdController::listAdd
householdAdd:
    path: /domacnost/pridat/{id}
    controller: App\Controller\Household\HouseholdController::add
mealList:
    path: /jidla
    controller: App\Controller\Meal\MealController::list
mealCreate:
    path: /jidlo/vytvorit
    controller: App\Controller\Meal\MealController::create
mealDetail:
  path: /jidlo/{url}
  controller: App\Controller\Meal\MealController::detail
mealEdit:
  path: /jidlo/upravit/{url}
  controller: App\Controller\Meal\MealController::edit
mealToggleFavorite:
  path: /jidlo/oblíbený/{url}
  controller: App\Controller\Meal\MealController::toggleFavorite